[
  ["{", "data"],
  ["", "application", "{", "data['application']"],
  ["", "", "name", "website", "data['application']['name']"],
  ["", "", "bootstrap", true, "data['application']['bootstrap']"],
  ["", "", "rootComponent", "{", "data['application']['rootComponent']"],
  [
    "",
    "",
    "",
    "name",
    "viewport",
    "data['application']['rootComponent']['name']",
  ],
  [
    "",
    "",
    "",
    "bindings",
    "{",
    "data['application']['rootComponent']['bindings']",
  ],
  [
    "",
    "",
    "",
    "",
    "input",
    "[",
    "data['application']['rootComponent']['bindings']['input']",
  ],
  ["", "", "", "", "", "input", "]"],
  [
    "",
    "",
    "",
    "",
    "output",
    "[",
    "data['application']['rootComponent']['bindings']['output']",
  ],
  ["", "", "", "", "", "output", "]"],
  ["", "", "", "", "bindings", "}"],
  [
    "",
    "",
    "",
    "properties",
    "[",
    "data['application']['rootComponent']['properties']",
  ],
  ["", "", "", "", "properties", "]"],
  [
    "",
    "",
    "",
    "methods",
    "[",
    "data['application']['rootComponent']['methods']",
  ],
  ["", "", "", "", "methods", "]"],
  [
    "",
    "",
    "",
    "components",
    "[",
    "data['application']['rootComponent']['components']",
  ],
  ["", "", "", "", "components", "]"],
  ["", "", "", "rootComponent", "}"],
  ["", "", "bindings", "{", "data['application']['bindings']"],
  ["", "", "", "input", "[", "data['application']['bindings']['input']"],
  ["", "", "", "", "input", "]"],
  ["", "", "", "output", "[", "data['application']['bindings']['output']"],
  ["", "", "", "", "output", "]"],
  ["", "", "", "bindings", "}"],
  ["", "", "application", "}"],
  ["}"],
];
